package service

import (
	"github.com/ronaksoft/ronykit"
	"github.com/ronaksoft/ronykit/std/bundle/rest"
	"github.com/ronaksoft/ronykit/std/contract"
	"github.com/ronaksoft/ronykit/std/service"
)

/*
   This Code is Auto-Generated by RonyDESC. Please DO NOT EDIT.
   Generated at:
*/

// IServiceA define the interface which MUST be implemented.
type IServiceA interface {
	Echo(ctx *ronykit.Context)
}

// serviceAWrapper
type serviceAWrapper struct {
	svc  IServiceA
	pre  []ronykit.Handler
	post []ronykit.Handler
}

func (x serviceAWrapper) echoContract() ronykit.Contract {
	return contract.New().
		SetSelector(
			rest.Route("GET", "/echo/:randomID").
				WithFactory(
					func() ronykit.Message {
						return &EchoRequest{}
					},
				),
		).
		SetHandler(x.svc.Echo)
}

func (x *serviceAWrapper) SetPreHandler(h ...ronykit.Handler) *serviceAWrapper {
	x.pre = append(x.pre, h...)

	return x
}

func (x *serviceAWrapper) SetPostHandler(h ...ronykit.Handler) *serviceAWrapper {
	x.post = append(x.post, h...)

	return x
}

func (x serviceAWrapper) Service() ronykit.Service {
	return service.New("ServiceA").
		AddContract(x.echoContract()).
		SetPreHandlers(x.pre...).
		SetPostHandlers(x.post...)
}

func NewServiceA(svc IServiceA) *serviceAWrapper {
	return &serviceAWrapper{
		svc: svc,
	}
}
